spring:
  jpa:
    generate-ddl: 'true'
    database: h2
    hibernate:
      ddl-auto: create
    show-sql: 'true'
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: 'true'
  datasource:
    url: jdbc:h2:mem:search
    driverClassName: org.h2.Driver
    password: ''
    generate-unique-name: 'false'
    username: sa
  h2:
    console:
      path: /h2-console
      enabled: 'true'
logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate:
        sql: DEBUG
    jpa: DEBUG
